Our team page commit
doyenify/doyenify pull request #4
Opened 2023-02-15 18:20 UTC by Dolybim

2023-02-23 18:07 UTC, OluyideO commented
there is need to resolve the conflict on this branch

2023-02-23 18:07 UTC, OluyideO requested changes

2023-02-23 18:15 UTC, OluyideO requested changes

2023-02-23 18:15 UTC, OluyideO commented on src/Pages/Contact.tsx
> +            // onSubmit={(values, actions) => handleSubmit(values.email, values.message)
If this comment is not useful let us remove it

2023-02-23 18:15 UTC, OluyideO commented on src/ourTeam.css
> +        /* height: 100vh; */
do we still need this

2023-02-24 17:45 UTC, Oluyide approved these changes

2023-02-25 14:54 UTC, merged