Features/contact page
doyenify/doyenify pull request #6
Opened 2023-02-20 10:26 UTC by Dolybim

2023-02-23 17:54 UTC, OluyideO approved these changes

2023-02-23 17:54 UTC, OluyideO commented on src/Pages/Contact.tsx
>  // const [message, setMessage] = useState('');
Let us remove these comments if they are not useful

2023-02-23 17:57 UTC, OluyideO commented on src/Pages/Contact.tsx
> +            // onSubmit={(values, actions) => handleSubmit(values.email, values.message)
let us remove unncessary comments

2023-02-23 18:00 UTC, OluyideO requested changes

2023-02-23 18:00 UTC, OluyideO commented
There is a conflict in  this branch please resolve conflicts

2023-02-23 21:33 UTC, Dolybim commented on src/Pages/Contact.tsx
>  // const [message, setMessage] = useState('');
alright, done

2023-02-23 21:36 UTC, Dolybim commented on src/ourTeam.css
> +        /* height: 100vh; */
done

2023-02-24 17:27 UTC, OluyideO approved these changes

2023-02-25 15:15 UTC, merged